# Generated by Django 3.2.7 on 2021-10-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='pdtId',
            field=models.IntegerField(),
        ),
    ]
