# Generated by Django 3.2.7 on 2021-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
