# Generated by Django 3.2.7 on 2021-10-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_orders_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
