# Generated by Django 3.2.7 on 2021-10-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodItems', models.BigIntegerField()),
                ('Rent', models.BigIntegerField()),
                ('Electricity', models.BigIntegerField()),
                ('TotalSalary', models.BigIntegerField()),
                ('OtherExpense', models.BigIntegerField()),
                ('CurrentDate', models.DateField()),
            ],
        ),
    ]
