# Generated by Django 3.2.7 on 2021-10-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='CurrentDate',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Electricity',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='OtherExpense',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Rent',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='TotalSalary',
        ),
    ]
