# Generated by Django 3.2.7 on 2021-10-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_auto_20211021_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
