# Generated by Django 3.2.7 on 2021-10-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='TotalExpense',
            field=models.BigIntegerField(default=0),
        ),
    ]
