# Generated by Django 3.2.7 on 2021-10-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_auto_20211022_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='Electricity',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='FoodItems',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='OtherExpense',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='Rent',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='TotalSalary',
            field=models.BigIntegerField(default=0),
        ),
    ]
